# **Data Cleaning & Preprocessing**



The dataset contains missing values, duplicate records, inconsistent values, and categorical variables that require transformation before machine learning can be applied.

The objectives of this stage are:

- Handle missing values
- Remove duplicate records
- Fix inconsistent data
- Convert data types where necessary
- Encode categorical variables
- Prepare the dataset for feature engineering and modeling

## **Load DataSet**

In [109]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\user\OneDrive\Desktop\Machine Learning Project\Data\hotel_bookings.csv")
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

## **Checking Missing Values**

In [110]:
df.isnull().sum().sort_values(ascending=False)

company                           112593
agent                              16340
country                              488
children                               4
arrival_date_month                     0
arrival_date_week_number               0
hotel                                  0
is_canceled                            0
stays_in_weekend_nights                0
arrival_date_day_of_month              0
adults                                 0
stays_in_week_nights                   0
babies                                 0
meal                                   0
lead_time                              0
arrival_date_year                      0
distribution_channel                   0
market_segment                         0
previous_bookings_not_canceled         0
is_repeated_guest                      0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
previous_cancellations                 0
deposit_type                           0
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

## **Handle Missing Values**

In [111]:
# children
df['children'] = df['children'].fillna(0)

# country
df['country'] = df['country'].fillna('Unknown')

# agent
df['agent'] = df['agent'].fillna(0)

# company
df.drop('company', axis=1, inplace=True)

Agent and company columns contain a large number of missing values.

These missing values do not necessarily indicate missing information but often represent bookings made without an associated travel agent or company.

Therefore, missing values were replaced with 0.

## **Verifying Missing Values**

In [112]:
df.isnull().sum().sort_values(ascending=False)

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

## Missing Value Treatment

The following actions were taken:

- Missing values in `children` were replaced with 0.
- Missing values in `country` were replaced with "Unknown".
- Missing values in `agent` were replaced with 0.
- The `company` column was removed because approximately 94% of its values were missing.

These decisions were made to preserve useful information while reducing noise.

## **Check Duplicate Records**

In [113]:
df.duplicated().sum()

np.int64(32001)

## **Removing Duplicates**

In [114]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

## **Outlier Detection And Removing**

In [115]:
outlier_columns = ['lead_time', 'adr']

for col in outlier_columns:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - (1.5 * IQR)
    upper_bound = Q3 + (1.5 * IQR)

    df = df[
        (df[col] >= lower_bound) &
        (df[col] <= upper_bound)
    ]

## **Fix Inconsistent Values**

In [116]:
df[
    (df['adults'] == 0) &
    (df['children'] == 0) &
    (df['babies'] == 0)
].shape

(164, 31)

In [117]:
df = df[
    ~(
        (df['adults'] == 0) &
        (df['children'] == 0) &
        (df['babies'] == 0)
    )
]

## **Convert Data Types**

## **Check Data Types**

In [118]:
df.dtypes

hotel                                 str
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                    str
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                  str
country                               str
market_segment                        str
distribution_channel                  str
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                    str
assigned_room_type                    str
booking_changes                     int64
deposit_type                          str
agent                             float64
days_in_waiting_list                int64
customer_type                         str
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                    str
reservation_status_date               str
dtype: object

## **Convert To Date Column**

In [119]:
df['reservation_status_date'] = pd.to_datetime(
    df['reservation_status_date']
)
df.info()

<class 'pandas.DataFrame'>
Index: 82479 entries, 2 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           82479 non-null  str
 1   is_canceled                     82479 non-null  int64
 2   lead_time                       82479 non-null  int64
 3   arrival_date_year               82479 non-null  int64
 4   arrival_date_month              82479 non-null  str
 5   arrival_date_week_number        82479 non-null  int64
 6   arrival_date_day_of_month       82479 non-null  int64
 7   stays_in_weekend_nights         82479 non-null  int64
 8   stays_in_week_nights            82479 non-null  int64
 9   adults                          82479 non-null  int64
 10  children                        82479 non-null  float64
 11  babies                          82479 non-null  int64
 12  meal                            82479 non-null  str
 13  country                         82479 non-null  str
 14  market_segment                  82479 non-null  str
 15  distribution_channel            82479 non-null  str
 16  is_repeated_guest               82479 non-null  int64
 17  previous_cancellations          82479 non-null  int64
 18  previous_bookings_not_canceled  82479 non-null  int64
 19  reserved_room_type              82479 non-null  str
 20  assigned_room_type              82479 non-null  str
 21  booking_changes                 82479 non-null  int64
 22  deposit_type                    82479 non-null  str
 23  agent                           82479 non-null  float64
 24  days_in_waiting_list            82479 non-null  int64
 25  customer_type                   82479 non-null  str
 26  adr                             82479 non-null  float64
 27  required_car_parking_spaces     82479 non-null  int64
 28  total_of_special_requests       82479 non-null  int64
 29  reservation_status              82479 non-null  str
 30  reservation_status_date         82479 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(3), int64(16), str(11)
memory usage: 20.1 MB

## **Check Cardinality Before Encoding**

In [120]:
categorical_columns = df.select_dtypes(include='string').columns

for col in categorical_columns:
    print(col, ":", df[col].nunique())

hotel : 2
arrival_date_month : 12
meal : 5
country : 175
market_segment : 8
distribution_channel : 5
reserved_room_type : 9
assigned_room_type : 11
deposit_type : 3
customer_type : 4
reservation_status : 3

# **Label Encoding**

In [121]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

label_cols = [
    'hotel',
    'deposit_type',
    'customer_type',
    'reservation_status'
]

for col in label_cols:
    df[col] = le.fit_transform(df[col])

df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
2,1,0,7,2015,July,27,1,0,1,1,...,0,0,0.0,0,2,75.00,0,0,1,2015-07-02
3,1,0,13,2015,July,27,1,0,1,1,...,0,0,304.0,0,2,75.00,0,0,1,2015-07-02
4,1,0,14,2015,July,27,1,0,2,2,...,0,0,240.0,0,2,98.00,0,1,1,2015-07-03
6,1,0,0,2015,July,27,1,0,2,2,...,0,0,0.0,0,2,107.00,0,0,1,2015-07-03
7,1,0,9,2015,July,27,1,0,2,2,...,0,0,303.0,0,2,103.00,0,1,1,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,0,23,2017,August,35,30,2,5,2,...,0,0,394.0,0,2,96.14,0,0,1,2017-09-06
119386,0,0,102,2017,August,35,31,2,5,3,...,0,0,9.0,0,2,225.43,0,2,1,2017-09-07
119387,0,0,34,2017,August,35,31,2,5,2,...,0,0,9.0,0,2,157.71,0,4,1,2017-09-07
119388,0,0,109,2017,August,35,31,2,5,2,...,0,0,89.0,0,2,104.40,0,0,1,2017-09-07
119389,0,0,205,2017,August,35,29,2,7,2,...,0,0,9.0,0,2,151.20,0,2,1,2017-09-07

# **One-Hot Encoding**

In [122]:
one_hot_cols = [
    'meal',
    'market_segment',
    'distribution_channel'
]

df = pd.get_dummies(
    df,
    columns=one_hot_cols,
    drop_first=True,
    dtype=int
)

In [123]:
print("Shape After Cleaning:", df.shape)

df.head()

Shape After Cleaning: (82479, 43)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined
2,1,0,7,2015,July,27,1,0,1,1,...,0,1,0,0,0,0,1,0,0,0
3,1,0,13,2015,July,27,1,0,1,1,...,1,0,0,0,0,0,0,0,0,0
4,1,0,14,2015,July,27,1,0,2,2,...,0,0,0,0,1,0,0,0,1,0
6,1,0,0,2015,July,27,1,0,2,2,...,0,1,0,0,0,0,1,0,0,0
7,1,0,9,2015,July,27,1,0,2,2,...,0,1,0,0,0,0,1,0,0,0

In [124]:
# Convert month
month_mapping = {
    'January':1,
    'February':2,
    'March':3,
    'April':4,
    'May':5,
    'June':6,
    'July':7,
    'August':8,
    'September':9,
    'October':10,
    'November':11,
    'December':12
}
df['arrival_date_month'] = df['arrival_date_month'].map(month_mapping)

# Drop country
df.drop('country', axis=1, inplace=True)

# One-hot encode room types
df = pd.get_dummies(
    df,
    columns=['reserved_room_type',
             'assigned_room_type'],
    drop_first=True,
    dtype=int
)

In [125]:
df.info()

<class 'pandas.DataFrame'>
Index: 82479 entries, 2 to 119389
Data columns (total 58 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           82479 non-null  int64
 1   is_canceled                     82479 non-null  int64
 2   lead_time                       82479 non-null  int64
 3   arrival_date_year               82479 non-null  int64
 4   arrival_date_month              82479 non-null  int64
 5   arrival_date_week_number        82479 non-null  int64
 6   arrival_date_day_of_month       82479 non-null  int64
 7   stays_in_weekend_nights         82479 non-null  int64
 8   stays_in_week_nights            82479 non-null  int64
 9   adults                          82479 non-null  int64
 10  children                        82479 non-null  float64
 11  babies                          82479 non-null  int64
 12  is_repeated_guest               82479 non-null  int64
 13  previous_cancellations          82479 non-null  int64
 14  previous_bookings_not_canceled  82479 non-null  int64
 15  booking_changes                 82479 non-null  int64
 16  deposit_type                    82479 non-null  int64
 17  agent                           82479 non-null  float64
 18  days_in_waiting_list            82479 non-null  int64
 19  customer_type                   82479 non-null  int64
 20  adr                             82479 non-null  float64
 21  required_car_parking_spaces     82479 non-null  int64
 22  total_of_special_requests       82479 non-null  int64
 23  reservation_status              82479 non-null  int64
 24  reservation_status_date         82479 non-null  datetime64[us]
 25  meal_FB                         82479 non-null  int64
 26  meal_HB                         82479 non-null  int64
 27  meal_SC                         82479 non-null  int64
 28  meal_Undefined                  82479 non-null  int64
 29  market_segment_Complementary    82479 non-null  int64
 30  market_segment_Corporate        82479 non-null  int64
 31  market_segment_Direct           82479 non-null  int64
 32  market_segment_Groups           82479 non-null  int64
 33  market_segment_Offline TA/TO    82479 non-null  int64
 34  market_segment_Online TA        82479 non-null  int64
 35  market_segment_Undefined        82479 non-null  int64
 36  distribution_channel_Direct     82479 non-null  int64
 37  distribution_channel_GDS        82479 non-null  int64
 38  distribution_channel_TA/TO      82479 non-null  int64
 39  distribution_channel_Undefined  82479 non-null  int64
 40  reserved_room_type_B            82479 non-null  int64
 41  reserved_room_type_C            82479 non-null  int64
 42  reserved_room_type_D            82479 non-null  int64
 43  reserved_room_type_E            82479 non-null  int64
 44  reserved_room_type_F            82479 non-null  int64
 45  reserved_room_type_G            82479 non-null  int64
 46  reserved_room_type_H            82479 non-null  int64
 47  reserved_room_type_L            82479 non-null  int64
 48  assigned_room_type_B            82479 non-null  int64
 49  assigned_room_type_C            82479 non-null  int64
 50  assigned_room_type_D            82479 non-null  int64
 51  assigned_room_type_E            82479 non-null  int64
 52  assigned_room_type_F            82479 non-null  int64
 53  assigned_room_type_G            82479 non-null  int64
 54  assigned_room_type_H            82479 non-null  int64
 55  assigned_room_type_I            82479 non-null  int64
 56  assigned_room_type_K            82479 non-null  int64
 57  assigned_room_type_L            82479 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(54)
memory usage: 37.1 MB

In [126]:
save_path = r"C:\Users\user\OneDrive\Desktop\Machine Learning Project\Data\hotel_bookings_cleaned_day_2.csv"

df.to_csv(save_path, index=False)

print("Saved Successfully")

Saved Successfully